version: '3.8'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./notebooks:/app/notebooks
      - ./models:/app/models
      - ./scripts:/app/scripts
      - ./Data:/app/Data
    container_name: python_notebook
